AWSTemplateFormatVersion: 2010-09-09
Description: |
  Simple example which creates EC2 instance with parameters 
  from the user in the create stack wizard
Parameters:
  HelloName:
    Description: Name to say Hello to in the web page
    Type: String
    Default: Guest
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: "ap-southeast-2a"
      ImageId: "ami-0646b10ec20a40c81"
      InstanceType: "t2.micro"
      UserData: 
        Fn::Base64: !Sub |
          #!/bin/bash
          yum install httpd -y
          service httpd start
          echo "<html><body><h1>Hello ${HelloName} from ${AWS::Region}</h1></body></html>" > /var/www/html/index.html
Outputs:
  InstanceId:
    Description: InstanceId of newly created EC2 instance
    Value: !Ref EC2Instance